local M = {}

local palette = require("superbloom.palette")

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local function groups()
  local p = palette

  return {
    Normal = { fg = p.text, bg = p.base },
    NormalNC = { fg = p.text, bg = p._nc },
    NormalFloat = { fg = p.text, bg = p.surface },
    FloatBorder = { fg = p.muted, bg = p.surface },
    FloatTitle = { fg = p.clarkia, bg = p.surface, bold = true },
    ColorColumn = { bg = p.surface },
    Conceal = { fg = p.muted },
    Cursor = { fg = p.base, bg = p.text },
    CursorLine = { bg = p.highlight_low },
    CursorLineNr = { fg = p.clarkia, bold = true },
    Directory = { fg = p.sea },
    EndOfBuffer = { fg = p.base },
    ErrorMsg = { fg = p.paintbrush, bold = true },
    Folded = { fg = p.subtle, bg = p.surface },
    IncSearch = { fg = p.base, bg = p.poppy },
    LineNr = { fg = p.muted },
    MatchParen = { fg = p.poppy, bg = p.highlight_med, bold = true },
    ModeMsg = { fg = p.sage, bold = true },
    MoreMsg = { fg = p.sage },
    NonText = { fg = p.muted },
    Pmenu = { fg = p.subtle, bg = p.surface },
    PmenuSel = { fg = p.text, bg = p.overlay },
    PmenuSbar = { bg = p.surface },
    PmenuThumb = { bg = p.highlight_high },
    Question = { fg = p.lupine },
    Search = { fg = p.base, bg = p.clarkia },
    SignColumn = { fg = p.muted, bg = p.base },
    SpecialKey = { fg = p.muted },
    SpellBad = { sp = p.paintbrush, undercurl = true },
    SpellCap = { sp = p.sky, undercurl = true },
    SpellLocal = { sp = p.lupine, undercurl = true },
    SpellRare = { sp = p.clarkia, undercurl = true },
    StatusLine = { fg = p.subtle, bg = p.surface },
    StatusLineNC = { fg = p.muted, bg = p.surface },
    Substitute = { fg = p.base, bg = p.paintbrush },
    TabLine = { fg = p.subtle, bg = p.surface },
    TabLineFill = { bg = p.surface },
    TabLineSel = { fg = p.text, bg = p.overlay },
    Title = { fg = p.clarkia, bold = true },
    VertSplit = { fg = p.muted },
    Visual = { bg = p.highlight_med },
    WarningMsg = { fg = p.poppy, bold = true },
    Whitespace = { fg = p.overlay },
    WildMenu = { fg = p.text, bg = p.overlay },
    WinSeparator = { fg = p.muted },
    IblIndent = { fg = p.overlay },
    IblScope = { fg = p.highlight_high },
    IndentBlanklineChar = { fg = p.overlay },
    IndentBlanklineContextChar = { fg = p.highlight_high },
    SnacksIndent = { fg = p.overlay },
    SnacksIndentScope = { fg = p.highlight_high },

    Comment = { fg = p.muted, italic = true },
    Constant = { fg = p.brodiaea },
    String = { fg = p.gold },
    Character = { fg = p.gold },
    Number = { fg = p.poppy },
    Boolean = { fg = p.poppy },
    Float = { fg = p.poppy },
    Identifier = { fg = p.text },
    Function = { fg = p.clarkia },
    Statement = { fg = p.lupine },
    Conditional = { fg = p.lupine },
    Repeat = { fg = p.lupine },
    Label = { fg = p.subtle },
    Operator = { fg = p.subtle },
    Keyword = { fg = p.lupine },
    Exception = { fg = p.lupine },
    PreProc = { fg = p.lupine },
    Include = { fg = p.lupine },
    Define = { fg = p.lupine },
    Macro = { fg = p.lupine },
    PreCondit = { fg = p.lupine },
    Type = { fg = p.brodiaea },
    StorageClass = { fg = p.lupine },
    Structure = { fg = p.brodiaea },
    Typedef = { fg = p.brodiaea },
    Special = { fg = p.poppy },
    SpecialChar = { fg = p.poppy },
    Tag = { fg = p.sage },
    Delimiter = { fg = p.subtle },
    Debug = { fg = p.paintbrush },
    Underlined = { fg = p.lupine, underline = true },
    Error = { fg = p.paintbrush },
    Todo = { fg = p.clarkia, bg = p.highlight_low, bold = true },

    DiagnosticError = { fg = p.paintbrush },
    DiagnosticWarn = { fg = p.poppy },
    DiagnosticInfo = { fg = p.brodiaea },
    DiagnosticHint = { fg = p.lupine },
    DiagnosticOk = { fg = p.sage },
    DiagnosticUnderlineError = { sp = p.paintbrush, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.poppy, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.brodiaea, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.lupine, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.sage, undercurl = true },
    DiagnosticVirtualTextError = { fg = p.paintbrush, bg = p.highlight_low },
    DiagnosticVirtualTextWarn = { fg = p.poppy, bg = p.highlight_low },
    DiagnosticVirtualTextInfo = { fg = p.brodiaea, bg = p.highlight_low },
    DiagnosticVirtualTextHint = { fg = p.lupine, bg = p.highlight_low },
    DiagnosticVirtualTextOk = { fg = p.sage, bg = p.highlight_low },
    DiagnosticSignError = { fg = p.paintbrush },
    DiagnosticSignWarn = { fg = p.poppy },
    DiagnosticSignInfo = { fg = p.brodiaea },
    DiagnosticSignHint = { fg = p.lupine },
    DiagnosticSignOk = { fg = p.sage },

    -- Background washes only; foreground left to syntax so code stays readable.
    DiffAdd = { bg = p.diff_add },
    DiffChange = { bg = p.diff_change },
    DiffDelete = { bg = p.diff_delete },
    DiffText = { bg = p.diff_text },
    Added = { fg = p.sage },
    Changed = { fg = p.poppy },
    Removed = { fg = p.paintbrush },
    GitSignsAdd = { fg = p.sage },
    GitSignsChange = { fg = p.poppy },
    GitSignsDelete = { fg = p.paintbrush },

    ["@variable"] = { fg = p.text },
    ["@variable.builtin"] = { fg = p.subtle },
    ["@variable.parameter"] = { fg = p.subtle, italic = true },
    ["@variable.member"] = { fg = p.subtle },
    ["@constant"] = { fg = p.brodiaea },
    ["@constant.builtin"] = { fg = p.poppy },
    ["@module"] = { fg = p.cream },
    ["@namespace"] = { fg = p.cream },
    ["@label"] = { fg = p.subtle },
    ["@string"] = { fg = p.gold },
    ["@string.documentation"] = { fg = p.muted, italic = true },
    ["@string.escape"] = { fg = p.poppy },
    ["@string.special"] = { fg = p.poppy },
    ["@character"] = { fg = p.gold },
    ["@number"] = { fg = p.poppy },
    ["@boolean"] = { fg = p.poppy },
    ["@float"] = { fg = p.poppy },
    ["@type"] = { fg = p.brodiaea },
    ["@type.builtin"] = { fg = p.brodiaea },
    ["@attribute"] = { fg = p.lupine },
    ["@property"] = { fg = p.subtle },
    ["@function"] = { fg = p.clarkia },
    ["@function.call"] = { fg = p.clarkia },
    ["@function.builtin"] = { fg = p.clarkia },
    ["@function.method"] = { fg = p.clarkia },
    ["@function.method.call"] = { fg = p.clarkia },
    ["@constructor"] = { fg = p.clarkia },
    ["@operator"] = { fg = p.subtle },
    ["@keyword"] = { fg = p.lupine },
    ["@keyword.import"] = { fg = p.lupine },
    ["@keyword.function"] = { fg = p.lupine },
    ["@keyword.operator"] = { fg = p.subtle },
    ["@keyword.return"] = { fg = p.lupine },
    ["@keyword.conditional"] = { fg = p.lupine },
    ["@keyword.repeat"] = { fg = p.lupine },
    ["@keyword.exception"] = { fg = p.lupine },
    ["@punctuation"] = { fg = p.subtle },
    ["@punctuation.bracket"] = { fg = p.subtle },
    ["@punctuation.delimiter"] = { fg = p.subtle },
    ["@punctuation.special"] = { fg = p.poppy },
    ["@tag"] = { fg = p.sage, italic = true },
    ["@tag.builtin"] = { fg = p.sage, italic = true },
    ["@tag.attribute"] = { fg = p.lupine },
    ["@tag.delimiter"] = { fg = p.subtle },
    ["@tag.tsx"] = { fg = p.sage, italic = true },
    ["@tag.builtin.tsx"] = { fg = p.sage, italic = true },
    ["@tag.attribute.tsx"] = { fg = p.lupine },
    ["@tag.delimiter.tsx"] = { fg = p.subtle },
    ["@comment"] = { fg = p.muted, italic = true },
    ["@comment.todo"] = { fg = p.clarkia, bg = p.highlight_low, bold = true },
    ["@comment.error"] = { fg = p.paintbrush },
    ["@comment.warning"] = { fg = p.poppy },
    ["@comment.note"] = { fg = p.brodiaea },
    ["@markup.heading.1"] = { fg = p.clarkia, bold = true },
    ["@markup.heading.2"] = { fg = p.clarkia, bold = true },
    ["@markup.heading.3"] = { fg = p.clarkia, bold = true },
    ["@markup.heading.4"] = { fg = p.clarkia, bold = true },
    ["@markup.heading.5"] = { fg = p.clarkia, bold = true },
    ["@markup.heading.6"] = { fg = p.clarkia, bold = true },
    ["@markup.link"] = { fg = p.brodiaea },
    ["@markup.link.url"] = { fg = p.brodiaea, underline = true },
    ["@markup.raw"] = { fg = p.sage },
    ["@diff.plus"] = { fg = p.sage },
    ["@diff.minus"] = { fg = p.paintbrush },
    ["@diff.delta"] = { fg = p.poppy },

    ["@lsp.type.class"] = { fg = p.brodiaea },
    ["@lsp.type.enum"] = { fg = p.brodiaea },
    ["@lsp.type.interface"] = { fg = p.brodiaea },
    ["@lsp.type.namespace"] = { fg = p.cream },
    ["@lsp.type.parameter"] = { fg = p.subtle, italic = true },
    ["@lsp.type.property"] = { fg = p.subtle },
    ["@lsp.type.type"] = { fg = p.brodiaea },
    ["@lsp.type.typeParameter"] = { fg = p.brodiaea },

    TelescopeNormal = { fg = p.text, bg = p.surface },
    TelescopeBorder = { fg = p.muted, bg = p.surface },
    TelescopePromptNormal = { fg = p.text, bg = p.surface },
    TelescopePromptBorder = { fg = p.muted, bg = p.surface },
    TelescopePromptPrefix = { fg = p.clarkia },
    TelescopeSelection = { fg = p.text, bg = p.overlay },
    TelescopeSelectionCaret = { fg = p.clarkia, bg = p.overlay },
    TelescopeMatching = { fg = p.poppy, bold = true },
    TelescopeTitle = { fg = p.sea, bold = true },

    SnacksPicker = { fg = p.text, bg = p.surface },
    SnacksPickerBorder = { fg = p.muted, bg = p.surface },
    SnacksPickerMatch = { fg = p.poppy, bold = true },
    SnacksPickerPrompt = { fg = p.clarkia },
    SnacksPickerSelected = { fg = p.text, bg = p.overlay },

    WhichKey = { fg = p.lupine },
    WhichKeyBorder = { fg = p.muted, bg = p.surface },
    WhichKeyDesc = { fg = p.brodiaea },
    WhichKeyFloat = { bg = p.surface },
    WhichKeyGroup = { fg = p.sea },
    WhichKeyIcon = { fg = p.clarkia },
    WhichKeySeparator = { fg = p.subtle },
    WhichKeyValue = { fg = p.clarkia },

    NotifyERRORBorder = { fg = p.paintbrush },
    NotifyERRORTitle = { fg = p.paintbrush },
    NotifyWARNBorder = { fg = p.poppy },
    NotifyWARNTitle = { fg = p.poppy },
    NotifyINFOBorder = { fg = p.brodiaea },
    NotifyINFOTitle = { fg = p.brodiaea },
    NotifyDEBUGBorder = { fg = p.muted },
    NotifyDEBUGTitle = { fg = p.muted },
    NotifyTRACEBorder = { fg = p.lupine },
    NotifyTRACETitle = { fg = p.lupine },

    NoiceCmdlinePopup = { fg = p.text, bg = p.surface },
    NoiceCmdlinePopupBorder = { fg = p.muted, bg = p.surface },
    NoiceCmdlineIcon = { fg = p.clarkia },
    TroubleNormal = { fg = p.text, bg = p.surface },
    TroubleText = { fg = p.text },

    BlinkCmpMenu = { fg = p.subtle, bg = p.surface },
    BlinkCmpMenuSelection = { fg = p.text, bg = p.overlay },
    BlinkCmpDoc = { fg = p.text, bg = p.surface },
    BlinkCmpDocBorder = { fg = p.muted, bg = p.surface },
    BlinkCmpLabelMatch = { fg = p.poppy, bold = true },
    BlinkCmpKind = { fg = p.sea },

    MiniFilesNormal = { fg = p.text, bg = p.surface },
    MiniFilesBorder = { fg = p.muted, bg = p.surface },
    MiniFilesTitle = { fg = p.sea, bg = p.surface },
    MiniFilesTitleFocused = { fg = p.clarkia, bg = p.surface, bold = true },
    MiniStatuslineModeNormal = { fg = p.base, bg = p.clarkia, bold = true },
    MiniStatuslineModeInsert = { fg = p.base, bg = p.sage, bold = true },
    MiniStatuslineModeVisual = { fg = p.base, bg = p.lupine, bold = true },
    MiniStatuslineModeReplace = { fg = p.base, bg = p.paintbrush, bold = true },
    MiniStatuslineModeCommand = { fg = p.base, bg = p.gold, bold = true },
    MiniStatuslineModeOther = { fg = p.base, bg = p.brodiaea, bold = true },

    RenderMarkdownH1 = { fg = p.clarkia, bold = true },
    RenderMarkdownH2 = { fg = p.clarkia, bold = true },
    RenderMarkdownH3 = { fg = p.clarkia, bold = true },
    RenderMarkdownH4 = { fg = p.clarkia, bold = true },
    RenderMarkdownH5 = { fg = p.clarkia, bold = true },
    RenderMarkdownH6 = { fg = p.clarkia, bold = true },
    RenderMarkdownCode = { bg = p.base },
    RenderMarkdownCodeInline = { fg = p.sage, bg = p.base },
  }
end

function M.apply()
  for group, opts in pairs(groups()) do
    hl(group, opts)
  end
end

return M
